pod_namespace: lighthouse
prowjob_namespace: lighthouse
postsubmits:
  lucareis/hello:
    - agent: tekton-pipeline
      branches:
        - master
        - main
      context: hello
      name: hello
      pipeline_run_spec:
        serviceAccountName: app-builder
        pipelineRef:
          name: hello-pipeline
tide:
  queries:
  - labels:
    - approved
    repos:
    - lucareis/config-lighthouse
    - lucareis/hello
