approve:
- lgtm_acts_as_approve: false
  repos:
  - lucareis/
  - lucareis/
  require_self_approval: true
config_updater:
  gzip: false
  maps:
    config.yaml:
      name: config
    plugins.yaml:
      name: plugins
triggers:
- repos:
  - lucareis/
  ignore_ok_to_test: false
  elide_skipped_contexts: false
plugins:
  lucareis/:
  - config-updater
  - approve
  - lgtm  
  lucareis/:
  - approve
  - lgtm
  - trigger
