approve:
- lgtm_acts_as_approve: false
  repos:
  - lucareis/lighthouse-config
  - lucareis/hello
  require_self_approval: true
config_updater:
  gzip: false
  maps:
    config.yaml:
      name: config
    plugins.yaml:
      name: plugins
triggers:
- repos:
  - lucareis/hello
  ignore_ok_to_test: false
  elide_skipped_contexts: false
plugins:
  lucareis/config-lighthouse:
  - config-updater
  - approve
  - lgtm  
  lucareis/hello:
  - approve
  - lgtm
  - trigger
